let products = [
  {
    title: "Sylthrene",
    image: "sylth.png",
    description: "stylish cafe chair",
    newPrice: 700,
    oldPrice: 3500,
    is_New: true,
    liked: false,
    discount: null,
  },
  {
    title: "Leviosa",
    image: "leviosa.png",
    description: "stylish cafe chair",
    newPrice: 1950,
    oldPrice: 5000,
    is_New: true,
    liked: false,
    discount: 30,
  },
  {
    title: "lolito",
    image: "lolito.png",
    description: "luxury big sofa",
    newPrice: 2000,
    oldPrice: 5000,
    is_New: true,
    liked: false,
    discount: null,
  },
  {
    title: "Grifo",
    image: "grifo.png",
    description: "night lamp",
    newPrice: 700,
    oldPrice: 3500,
    is_New: true,
    liked: false,
    discount: 50,
  },
  {
    title: "Grifo",
    image: "grifo.png",
    description: "night lamp",
    newPrice: 700,
    oldPrice: 3500,
    is_New: true,
    liked: false,
    discount: 50,
  },
  {
    title: "Muggo",
    image: "muggo.png",
    description: "small mug",
    newPrice: 700,
    oldPrice: 3500,
    is_New: true,
    liked: false,
    discount: 15,
  },
  {
    title: "Pingky",
    image: "pingky.png",
    description: "cute bed set",
    newPrice: 700,
    oldPrice: 3500,
    is_New: true,
    liked: false,
    discount: 12,
  },
  {
    title: "Potty",
    image: "potty.png",
    description: "minimalist flower pot",
    newPrice: 700,
    oldPrice: 3500,
    is_New: true,
    liked: false,
    discount: null,
  },
  {
    title: "Sylthrene",
    image: "sylth.png",
    description: "stylish cafe chair",
    newPrice: 700,
    oldPrice: 3500,
    is_New: true,
    liked: false,
    discount: null,
  },
  {
    title: "Pingky",
    image: "pingky.png",
    description: "cute bed set",
    newPrice: 700,
    oldPrice: 3500,
    is_New: true,
    liked: false,
    discount: 12,
  },
  {
    title: "Grifo",
    image: "grifo.png",
    description: "night lamp",
    newPrice: 700,
    oldPrice: 3500,
    is_New: true,
    liked: false,
    discount: 50,
  },
  {
    title: "Grifo",
    image: "grifo.png",
    description: "night lamp",
    newPrice: 700,
    oldPrice: 3500,
    is_New: true,
    liked: false,
    discount: 50,
  },
];

export default products;
